spring:
  datasource:
    url: jdbc:h2:mem:file/data.sql
    username: root
    password: ola24oluwa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true